//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajedrez.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF5FFFB")]
        public string ColorCasillasBlancas {
            get {
                return ((string)(this["ColorCasillasBlancas"]));
            }
            set {
                this["ColorCasillasBlancas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF4182BB")]
        public string ColorCasillasNegras {
            get {
                return ((string)(this["ColorCasillasNegras"]));
            }
            set {
                this["ColorCasillasNegras"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alpha")]
        public string ConjuntoPiezas {
            get {
                return ((string)(this["ConjuntoPiezas"]));
            }
            set {
                this["ConjuntoPiezas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CoronarSiempreDama {
            get {
                return ((bool)(this["CoronarSiempreDama"]));
            }
            set {
                this["CoronarSiempreDama"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CaracteresPieza {
            get {
                return ((int)(this["CaracteresPieza"]));
            }
            set {
                this["CaracteresPieza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public uint TamañoLetraJugadas {
            get {
                return ((uint)(this["TamañoLetraJugadas"]));
            }
            set {
                this["TamañoLetraJugadas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF191919")]
        public string BackgroundJugadas {
            get {
                return ((string)(this["BackgroundJugadas"]));
            }
            set {
                this["BackgroundJugadas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF292929")]
        public string BackgroundJugadores {
            get {
                return ((string)(this["BackgroundJugadores"]));
            }
            set {
                this["BackgroundJugadores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF111111")]
        public string BackgroundReloj {
            get {
                return ((string)(this["BackgroundReloj"]));
            }
            set {
                this["BackgroundReloj"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SePuedeDeshacerEnJuego {
            get {
                return ((bool)(this["SePuedeDeshacerEnJuego"]));
            }
            set {
                this["SePuedeDeshacerEnJuego"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("stockfish_20011801_x64.exe")]
        public string Motor {
            get {
                return ((string)(this["Motor"]));
            }
            set {
                this["Motor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF111111")]
        public string BackgroundMotor {
            get {
                return ((string)(this["BackgroundMotor"]));
            }
            set {
                this["BackgroundMotor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SePuedeExigirJugada {
            get {
                return ((bool)(this["SePuedeExigirJugada"]));
            }
            set {
                this["SePuedeExigirJugada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public string ProfundidadAnalisis {
            get {
                return ((string)(this["ProfundidadAnalisis"]));
            }
            set {
                this["ProfundidadAnalisis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int CantidadDeLineasAnalisis {
            get {
                return ((int)(this["CantidadDeLineasAnalisis"]));
            }
            set {
                this["CantidadDeLineasAnalisis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string HilosAnalisis {
            get {
                return ((string)(this["HilosAnalisis"]));
            }
            set {
                this["HilosAnalisis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public string HashAnalisis {
            get {
                return ((string)(this["HashAnalisis"]));
            }
            set {
                this["HashAnalisis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MoverArrastrando {
            get {
                return ((bool)(this["MoverArrastrando"]));
            }
            set {
                this["MoverArrastrando"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOPJUAN\\SQLEXPRESS;Initial Catalog=Ajedrez;Integrated Security=Tr" +
            "ue")]
        public string AjedrezConnectionString {
            get {
                return ((string)(this["AjedrezConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EliminarDirectamente {
            get {
                return ((bool)(this["EliminarDirectamente"]));
            }
            set {
                this["EliminarDirectamente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public string ProfundidadConTiempoIlimitado {
            get {
                return ((string)(this["ProfundidadConTiempoIlimitado"]));
            }
            set {
                this["ProfundidadConTiempoIlimitado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF111111")]
        public string BackgroundBaseDeDatos {
            get {
                return ((string)(this["BackgroundBaseDeDatos"]));
            }
            set {
                this["BackgroundBaseDeDatos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF1E1E1E")]
        public string BackgroundDataGrid {
            get {
                return ((string)(this["BackgroundDataGrid"]));
            }
            set {
                this["BackgroundDataGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF101010")]
        public string BackgroundDataGridRow {
            get {
                return ((string)(this["BackgroundDataGridRow"]));
            }
            set {
                this["BackgroundDataGridRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF151515")]
        public string BackgroundDataGridRowAlternativo {
            get {
                return ((string)(this["BackgroundDataGridRowAlternativo"]));
            }
            set {
                this["BackgroundDataGridRowAlternativo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF1E1E1E")]
        public string Background {
            get {
                return ((string)(this["Background"]));
            }
            set {
                this["Background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF90EE90")]
        public string BackgroundBotones {
            get {
                return ((string)(this["BackgroundBotones"]));
            }
            set {
                this["BackgroundBotones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF383838")]
        public string BackgroundMenu {
            get {
                return ((string)(this["BackgroundMenu"]));
            }
            set {
                this["BackgroundMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF202020")]
        public string BackgroundBarraMenu {
            get {
                return ((string)(this["BackgroundBarraMenu"]));
            }
            set {
                this["BackgroundBarraMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF404040")]
        public string BackgroundComboBox {
            get {
                return ((string)(this["BackgroundComboBox"]));
            }
            set {
                this["BackgroundComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFCCCCCC")]
        public string ColorTexto {
            get {
                return ((string)(this["ColorTexto"]));
            }
            set {
                this["ColorTexto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFCCCCCC")]
        public string ColorTextoBaseDeDatos {
            get {
                return ((string)(this["ColorTextoBaseDeDatos"]));
            }
            set {
                this["ColorTextoBaseDeDatos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFCCCCCC")]
        public string ColorTextoDataGrid {
            get {
                return ((string)(this["ColorTextoDataGrid"]));
            }
            set {
                this["ColorTextoDataGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFCCCCCC")]
        public string ColorTextoJugadas {
            get {
                return ((string)(this["ColorTextoJugadas"]));
            }
            set {
                this["ColorTextoJugadas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFCCCCCC")]
        public string ColorTextoJugadores {
            get {
                return ((string)(this["ColorTextoJugadores"]));
            }
            set {
                this["ColorTextoJugadores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFCCCCCC")]
        public string ColorTextoMotor {
            get {
                return ((string)(this["ColorTextoMotor"]));
            }
            set {
                this["ColorTextoMotor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFCCCCCC")]
        public string ColorTextoReloj {
            get {
                return ((string)(this["ColorTextoReloj"]));
            }
            set {
                this["ColorTextoReloj"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public string ColorTextoBotones {
            get {
                return ((string)(this["ColorTextoBotones"]));
            }
            set {
                this["ColorTextoBotones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFCCCCCC")]
        public string ColorTextoMenu {
            get {
                return ((string)(this["ColorTextoMenu"]));
            }
            set {
                this["ColorTextoMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFCCCCCC")]
        public string ColorTextoBarraMenu {
            get {
                return ((string)(this["ColorTextoBarraMenu"]));
            }
            set {
                this["ColorTextoBarraMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFCCCCCC")]
        public string ColorTextoComboBox {
            get {
                return ((string)(this["ColorTextoComboBox"]));
            }
            set {
                this["ColorTextoComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFCCCCCC")]
        public string ColorTextoTextBox {
            get {
                return ((string)(this["ColorTextoTextBox"]));
            }
            set {
                this["ColorTextoTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF404040")]
        public string BackgroundTextBox {
            get {
                return ((string)(this["BackgroundTextBox"]));
            }
            set {
                this["BackgroundTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF404040")]
        public string BackgroundListBox {
            get {
                return ((string)(this["BackgroundListBox"]));
            }
            set {
                this["BackgroundListBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFCCCCCC")]
        public string ColorTextoListBox {
            get {
                return ((string)(this["ColorTextoListBox"]));
            }
            set {
                this["ColorTextoListBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFCC0000")]
        public string ColorTextoError {
            get {
                return ((string)(this["ColorTextoError"]));
            }
            set {
                this["ColorTextoError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF030303")]
        public string BackgroundDataGridHeader {
            get {
                return ((string)(this["BackgroundDataGridHeader"]));
            }
            set {
                this["BackgroundDataGridHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFCCCCCC")]
        public string ColorTextoDataGridHeader {
            get {
                return ((string)(this["ColorTextoDataGridHeader"]));
            }
            set {
                this["ColorTextoDataGridHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF008000")]
        public string ColorBordeCasillaSeleccionada {
            get {
                return ((string)(this["ColorBordeCasillaSeleccionada"]));
            }
            set {
                this["ColorBordeCasillaSeleccionada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AvisarReiniciar {
            get {
                return ((bool)(this["AvisarReiniciar"]));
            }
            set {
                this["AvisarReiniciar"] = value;
            }
        }
    }
}
